# Generated by Django 4.1.5 on 2024-09-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/.2024-09-12.18-54-02'),
        ),
    ]
